[env:m5stack-atoms3]
platform = espressif32
board = m5stack-atoms3
framework = arduino

; AtomS3Rの8MB Octal PSRAMを正常に認識させるための設定
board_build.arduino.memory_type = qio_opi

build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; 依存ライブラリの明示（M5Unifiedを追加）
lib_deps = 
    m5stack/M5Unified
    m5stack/M5GFX

; シリアルモニターの通信速度設定
monitor_speed = 115200